/* GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Source: src/tokens/figma-tokens.json (exported from Figma bBtnBaKCvMRYylxj0Ghp2q)
 */

export const color = {
  'surfaceBase': 'var(--ds-surface-base)',
  'surfaceBaseHover': 'var(--ds-surface-base-hover)',
  'surfaceElevated': 'var(--ds-surface-elevated)',
  'surfaceSunken': 'var(--ds-surface-sunken)',
  'surfaceSelected': 'var(--ds-surface-selected)',
  'surfaceSelectedHover': 'var(--ds-surface-selected-hover)',
  'surfaceNeutralSubtle': 'var(--ds-surface-neutral-subtle)',
  'surfaceYellowSubtle': 'var(--ds-surface-yellow-subtle)',
  'surfaceGreenSubtle': 'var(--ds-surface-green-subtle)',
  'surfaceBlueSubtle': 'var(--ds-surface-blue-subtle)',
  'surfaceBrownSubtle': 'var(--ds-surface-brown-subtle)',
  'contentPrimary': 'var(--ds-content-primary)',
  'contentSecondary': 'var(--ds-content-secondary)',
  'contentSecondaryAlt': 'var(--ds-content-secondary-alt)',
  'contentTertiary': 'var(--ds-content-tertiary)',
  'contentTertiaryAlt': 'var(--ds-content-tertiary-alt)',
  'contentAccent': 'var(--ds-content-accent)',
  'contentOnYellow': 'var(--ds-content-on-yellow)',
  'contentOnGreen': 'var(--ds-content-on-green)',
  'contentOnBlue': 'var(--ds-content-on-blue)',
  'contentOnBrown': 'var(--ds-content-on-brown)',
  'borderDefault': 'var(--ds-border-default)',
} as const;

export const spacing = {
  '0': 'var(--ds-spacing-0)',
  '2': 'var(--ds-spacing-2)',
  '4': 'var(--ds-spacing-4)',
  '6': 'var(--ds-spacing-6)',
  '8': 'var(--ds-spacing-8)',
  '12': 'var(--ds-spacing-12)',
  '16': 'var(--ds-spacing-16)',
  '20': 'var(--ds-spacing-20)',
  '24': 'var(--ds-spacing-24)',
  '32': 'var(--ds-spacing-32)',
  '40': 'var(--ds-spacing-40)',
} as const;

export const radius = {
  '4': 'var(--ds-radius-4)',
  '6': 'var(--ds-radius-6)',
  '8': 'var(--ds-radius-8)',
} as const;

export const size = {
  'indicator': 'var(--ds-size-indicator)',
  'icon2xs': 'var(--ds-size-icon-2xs)',
  'iconXs': 'var(--ds-size-icon-xs)',
  'iconSm': 'var(--ds-size-icon-sm)',
  'iconMd': 'var(--ds-size-icon-md)',
  'controlMd': 'var(--ds-size-control-md)',
  'rowHeight': 'var(--ds-size-row-height)',
  'columnSm': 'var(--ds-size-column-sm)',
  'columnXs': 'var(--ds-size-column-xs)',
  'sidebar': 'var(--ds-size-sidebar)',
  'navSubheader': 'var(--ds-size-nav-subheader)',
  'pageHeader': 'var(--ds-size-page-header)',
  'filterBar': 'var(--ds-size-filter-bar)',
  'pageGutter': 'var(--ds-size-page-gutter)',
} as const;

export const border = {
  'widthThin': 'var(--ds-border-width-thin)',
  'widthThick': 'var(--ds-border-width-thick)',
} as const;

/** Composite text styles, mirroring the four Figma text styles 1:1. */
export const textStyle = {
  'title': {
    fontFamily: "var(--ds-font-family-default)",
    fontSize: "var(--ds-font-size-lg)",
    lineHeight: "var(--ds-font-line-height-lg)",
    fontWeight: "var(--ds-font-weight-semibold)",
    letterSpacing: "var(--ds-font-tracking-none)",
  },
  'body-strong': {
    fontFamily: "var(--ds-font-family-default)",
    fontSize: "var(--ds-font-size-md)",
    lineHeight: "var(--ds-font-line-height-md)",
    fontWeight: "var(--ds-font-weight-medium)",
    letterSpacing: "var(--ds-font-tracking-tight)",
  },
  'body': {
    fontFamily: "var(--ds-font-family-default)",
    fontSize: "var(--ds-font-size-md)",
    lineHeight: "var(--ds-font-line-height-md)",
    fontWeight: "var(--ds-font-weight-regular)",
    letterSpacing: "var(--ds-font-tracking-tight)",
  },
  'label': {
    fontFamily: "var(--ds-font-family-default)",
    fontSize: "var(--ds-font-size-sm)",
    lineHeight: "var(--ds-font-line-height-sm)",
    fontWeight: "var(--ds-font-weight-medium)",
    letterSpacing: "var(--ds-font-tracking-none)",
  },
} as const;

export type ColorToken = keyof typeof color;
export type SpacingToken = keyof typeof spacing;
export type RadiusToken = keyof typeof radius;
export type SizeToken = keyof typeof size;
export type TextStyleToken = keyof typeof textStyle;

/** The tag palette, driven entirely by semantic tokens. */
export const TAG_TYPES = ['neutral', 'yellow', 'green', 'blue', 'brown'] as const;
export type TagType = (typeof TAG_TYPES)[number];
