/**
 * Generates the token layer from figma-tokens.json.
 *
 * Run: npm run tokens
 *
 * Emits:
 *   src/tokens/tokens.css  — CSS custom properties, light + dark
 *   src/tokens/tokens.ts   — typed constants and text-style definitions
 *
 * Primitives are intentionally NOT emitted. Components can only reach
 * semantic tokens, which is what keeps the Figma/code contract honest.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const src = JSON.parse(readFileSync(join(root, 'src/tokens/figma-tokens.json'), 'utf8'));

/**
 * Figma variable name -> CSS-safe slug.
 * Handles the capitals, spaces and slashes Figma allows:
 *   `Surface/base`               -> `surface-base`
 *   `Tag Button/Content/on-blue` -> `tag-button-content-on-blue`
 */
const slug = (s) =>
  String(s)
    .trim()
    .toLowerCase()
    .replace(/[/\s_]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

/** `Surface/base` -> `--ds-surface-base` */
const cssVar = (...parts) => `--ds-${slug(parts.join('-'))}`;
/** `Surface/base` -> `surfaceBase`, `line-height/md` -> `lineHeightMd` */
const camel = (s) => slug(s).replace(/-(\w)/g, (_, c) => c.toUpperCase());

const px = (n) => (n === 0 ? '0px' : `${n}px`);

// ---------------------------------------------------------------- tokens.css
const light = [];
const dark = [];

// Colour names already carry their own group (Surface/, Content/, Border/),
// so they are slugged as-is rather than given an extra prefix.
for (const [name, val] of Object.entries(src.color)) {
  light.push(`  ${cssVar(name)}: ${val.light};`);
  dark.push(`  ${cssVar(name)}: ${val.dark};`);
}
for (const [k, v] of Object.entries(src.spacing)) light.push(`  ${cssVar('spacing', k)}: ${px(v)};`);
for (const [k, v] of Object.entries(src.radius)) light.push(`  ${cssVar('radius', k)}: ${px(v)};`);
for (const [k, v] of Object.entries(src.size)) light.push(`  ${cssVar('size', k)}: ${px(v)};`);
for (const [k, v] of Object.entries(src.border)) light.push(`  ${cssVar('border', k)}: ${px(v)};`);
for (const [k, v] of Object.entries(src.font)) {
  if (k.startsWith('family/')) light.push(`  ${cssVar('font', k)}: "${v}", ui-sans-serif, system-ui, sans-serif;`);
  else if (k.startsWith('weight/')) light.push(`  ${cssVar('font', k)}: ${v};`);
  else if (k.startsWith('tracking/')) light.push(`  ${cssVar('font', k)}: ${v}px;`);
  else light.push(`  ${cssVar('font', k)}: ${px(v)};`);
}

const banner = `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand.
 * Source: src/tokens/figma-tokens.json (exported from Figma ${src.$meta.fileKey})
 */`;

const css = `${banner}

:root {
${light.join('\n')}
}

/* Explicit override wins in both directions so the theme toggle always works. */
:root[data-theme='dark'] {
${dark.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${dark.map((l) => '  ' + l).join('\n')}
  }
}
`;
writeFileSync(join(root, 'src/tokens/tokens.css'), css);

// ----------------------------------------------------------------- tokens.ts
const varRef = (...p) => `var(${cssVar(...p)})`;

const group = (obj, prefix, transform = (k) => camel(k)) =>
  Object.keys(obj)
    .map((k) => `  '${transform(k)}': '${varRef(prefix, k)}',`)
    .join('\n');

const textStyles = Object.entries(src.textStyles)
  .map(
    ([name, s]) => `  '${name}': {
    fontFamily: ${JSON.stringify(varRef('font', 'family/default'))},
    fontSize: ${JSON.stringify(varRef('font', `size/${s.size}`))},
    lineHeight: ${JSON.stringify(varRef('font', `line-height/${s.lineHeight}`))},
    fontWeight: ${JSON.stringify(varRef('font', `weight/${s.weight}`))},
    letterSpacing: ${JSON.stringify(varRef('font', `tracking/${s.tracking}`))},
  },`
  )
  .join('\n');

const ts = `${banner.replace('/*', '/*').replace(' */', ' */')}

export const color = {
${Object.keys(src.color).map((k) => `  '${camel(k)}': '${varRef(k)}',`).join('\n')}
} as const;

export const spacing = {
${Object.keys(src.spacing).map((k) => `  '${k}': '${varRef('spacing', k)}',`).join('\n')}
} as const;

export const radius = {
${Object.keys(src.radius).map((k) => `  '${k}': '${varRef('radius', k)}',`).join('\n')}
} as const;

export const size = {
${group(src.size, 'size')}
} as const;

export const border = {
${group(src.border, 'border')}
} as const;

/** Composite text styles, mirroring the four Figma text styles 1:1. */
export const textStyle = {
${textStyles}
} as const;

export type ColorToken = keyof typeof color;
export type SpacingToken = keyof typeof spacing;
export type RadiusToken = keyof typeof radius;
export type SizeToken = keyof typeof size;
export type TextStyleToken = keyof typeof textStyle;

/** The tag palette, driven entirely by semantic tokens. */
export const TAG_TYPES = ['neutral', 'yellow', 'green', 'blue', 'brown'] as const;
export type TagType = (typeof TAG_TYPES)[number];
`;
writeFileSync(join(root, 'src/tokens/tokens.ts'), ts);

const counts = {
  color: Object.keys(src.color).length,
  spacing: Object.keys(src.spacing).length,
  radius: Object.keys(src.radius).length,
  size: Object.keys(src.size).length,
  border: Object.keys(src.border).length,
  font: Object.keys(src.font).length,
  textStyles: Object.keys(src.textStyles).length,
};
console.log('Generated tokens.css + tokens.ts');
console.table(counts);
